export enum Intent {
  BOOK_APPOINTMENT   = 'BOOK_APPOINTMENT',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
  VIEW_APPOINTMENTS  = 'VIEW_APPOINTMENTS',
  CHECK_AVAILABILITY = 'CHECK_AVAILABILITY',
  UNKNOWN            = 'UNKNOWN',
}
